### ISSUE TITLE
Sphinx Documentation Deploy

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/softwaremanagement#30]
Task Description: Deploy a single documentation engine (e.g., Sphinx) across ASC projects (ISIS, ALE, knoten, usgscsm, plio, AutoCNet) that supports versioned documentation

**Comment by ladoramkershner** [comment]
As part of the FY21 Documentation task we are integrating the Sphinx documentation engine to the following ASC projects:
- ale
- plio
- usgscsm
- AutoCNet
- knoten
- (stretch) ISIS (developer documentation only)

Sphinx is not being applied to the ISIS application documentation because it cannot parse the xml which holds the application overview, parameter information, and examples. To keep the same level of documentation we have decided not to use Sphinx on ISIS application docs. This work has thus far not included:
- PyHAT (not slated)
- plurmy (not slated)
- pysis (not slated)
- pfeffernusse (not slated)

**Comment by ladoramkershner** [comment]
Relevant PRs associated with integrating Sphinx into the ASC projects are:
ALE
- [404](https://github.com/USGS-Astrogeology/ale/pull/404)
- [405](https://github.com/USGS-Astrogeology/ale/pull/405)
- [406](https://github.com/USGS-Astrogeology/ale/pull/406)
- [407](https://github.com/USGS-Astrogeology/ale/pull/407)
- [408](https://github.com/USGS-Astrogeology/ale/pull/408)
- [418](https://github.com/USGS-Astrogeology/ale/pull/418)
- [419](https://github.com/USGS-Astrogeology/ale/pull/419)

PLIO
- [159](https://github.com/USGS-Astrogeology/plio/pull/159)

USGSCSM
- [332](https://github.com/USGS-Astrogeology/usgscsm/pull/332)

AUTOCNET
 - [532](https://github.com/USGS-Astrogeology/autocnet/pull/532) > still open 

KNOTEN
- [86](https://github.com/USGS-Astrogeology/knoten/pull/86)

**Comment by ladoramkershner** [comment]
I am closing because all baseline goals were met with deploying Sphinx to ASC project (excluding ISIS dev docs, which was a strech)
