### ISSUE TITLE
Update Calibration Apps to Use Remote SPICE

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/softwaremanagement#34]
Task Description: Update nine calibration applications that are furnishing kernels to support using the remotely accessible SPICE server. Applications identified: (1) amicacal, (2) ctxcal, (3) mical, (4) lrowaccal, (5) moccal, (6) mdiscal, (7) hical, (8) vikcal, (9) gllssical.

**Comment by kberryUSGS** [comment]
This work was completed. See: https://github.com/USGS-Astrogeology/ISIS3/issues/4303. The issue contains links to the individual PRs for each calibration application. 

Notes:
* `mical` could not be updated because it was not possible to spiceinit a MER image, and the only kernels furnshed in it were in the "base" kernels area, which is 
* `shadow` and `hjitreg` were also updated to remove furnsh calls as part of this sprint.
