### ISSUE TITLE
Addition of 3 registration techniques

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/softwaremanagement#76]
Task Description: Identification of three image registration techniques that could help improve registration of challenging data sets

**Comment by jessemapel** [comment]
Done. We tested:

- Mutual Information: [autocnet #559](https://github.com/USGS-Astrogeology/autocnet/pull/559) adds this to autocnet.
- Phase matching with geometric transformation: [autocnet #556](https://github.com/USGS-Astrogeology/autocnet/pull/556) made it so that we can use the existing phase matching and geometric correction together.
- Fourier-Mellin: [autocnet #558](https://github.com/USGS-Astrogeology/autocnet/pull/558) added this matcher


I am going to leave this issue open until the MI matchet PR gets merged though.
